package main

import (
	"encoding/json"
	"io"
	"sync"
	"sync/atomic"
	"time"

	"github.com/B-A-M-N/gripline/internal/observability"
	"github.com/B-A-M-N/gripline/internal/proxy"
)

// jsonlObserver is the stock executable's bounded, single-writer telemetry
// sink. Admission never waits on stderr or a slow collector: overflow is
// counted and reported periodically while the process is running.
type jsonlObserver struct {
	writer       io.Writer
	queue        chan any
	done         chan struct{}
	wg           sync.WaitGroup
	dropsTotal   atomic.Uint64
	dropsPending atomic.Uint64
	sinkFailures atomic.Uint64
	once         sync.Once
}

type completionLog struct {
	Type  string                `json:"type"`
	Event proxy.CompletionEvent `json:"event"`
}

type admissionLog struct {
	Type   string                        `json:"type"`
	Record *observability.DecisionRecord `json:"record"`
}

func newJSONLObserver(w io.Writer) *jsonlObserver {
	o := &jsonlObserver{writer: w, queue: make(chan any, 256), done: make(chan struct{})}
	o.wg.Add(1)
	go o.run()
	return o
}

func (o *jsonlObserver) run() {
	defer o.wg.Done()
	enc := json.NewEncoder(o.writer)
	write := func(value any) {
		if err := enc.Encode(value); err != nil {
			o.sinkFailures.Add(1)
		}
	}
	reportDrops := func() {
		if dropped := o.dropsPending.Swap(0); dropped > 0 {
			write(struct {
				Type    string `json:"type"`
				Dropped uint64 `json:"dropped"`
			}{Type: "telemetry_overflow", Dropped: dropped})
		}
	}
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	for {
		select {
		case ev := <-o.queue:
			write(ev)
		case <-ticker.C:
			reportDrops()
		case <-o.done:
			for {
				select {
				case ev := <-o.queue:
					write(ev)
				default:
					reportDrops()
					return
				}
			}
		}
	}
}

// TelemetryStats reports sink health without making authorization depend on
// the best-effort JSONL channel.
type TelemetryStats struct {
	Dropped      uint64 `json:"dropped"`
	SinkFailures uint64 `json:"sink_failures"`
}

func (o *jsonlObserver) Stats() TelemetryStats {
	return TelemetryStats{Dropped: o.dropsTotal.Load(), SinkFailures: o.sinkFailures.Load()}
}

func (o *jsonlObserver) enqueue(ev any) {
	select {
	case <-o.done:
		o.dropsTotal.Add(1)
		o.dropsPending.Add(1)
	case o.queue <- ev:
	default:
		o.dropsTotal.Add(1)
		o.dropsPending.Add(1)
	}
}

func (o *jsonlObserver) ObserveAdmission(record *observability.DecisionRecord) {
	o.enqueue(admissionLog{Type: "admission", Record: record})
}

func (o *jsonlObserver) ObserveCompletion(event proxy.CompletionEvent) {
	// CompletionEvent contains only safe codes/status/error metadata. The error
	// text is generated by internal providers, never by an external secret.
	o.enqueue(completionLog{Type: "completion", Event: event})
}

func (o *jsonlObserver) Close() error {
	o.once.Do(func() {
		close(o.done)
		o.wg.Wait()
	})
	return nil
}
