package main

import (
	"encoding/json"
	"io"
	"sync"
	"sync/atomic"

	"github.com/B-A-M-N/gripline/internal/observability"
	"github.com/B-A-M-N/gripline/internal/proxy"
)

// jsonlObserver is the stock executable's bounded, single-writer telemetry
// sink. Admission never waits on stderr or a slow collector: overflow is
// counted and reported after the queue drains.
type jsonlObserver struct {
	writer io.Writer
	queue  chan any
	done   chan struct{}
	wg     sync.WaitGroup
	drops  atomic.Uint64
	once   sync.Once
}

type completionLog struct {
	Type  string                `json:"type"`
	Event proxy.CompletionEvent `json:"event"`
}

type admissionLog struct {
	Type   string                        `json:"type"`
	Record *observability.DecisionRecord `json:"record"`
}

func newJSONLObserver(w io.Writer) *jsonlObserver {
	o := &jsonlObserver{writer: w, queue: make(chan any, 256), done: make(chan struct{})}
	o.wg.Add(1)
	go o.run()
	return o
}

func (o *jsonlObserver) run() {
	defer o.wg.Done()
	enc := json.NewEncoder(o.writer)
	for ev := range o.queue {
		_ = enc.Encode(ev)
	}
	if dropped := o.drops.Load(); dropped > 0 {
		_ = enc.Encode(struct {
			Type    string `json:"type"`
			Dropped uint64 `json:"dropped"`
		}{Type: "telemetry_overflow", Dropped: dropped})
	}
}

func (o *jsonlObserver) enqueue(ev any) {
	select {
	case o.queue <- ev:
	default:
		o.drops.Add(1)
	}
}

func (o *jsonlObserver) ObserveAdmission(record *observability.DecisionRecord) {
	o.enqueue(admissionLog{Type: "admission", Record: record})
}

func (o *jsonlObserver) ObserveCompletion(event proxy.CompletionEvent) {
	// CompletionEvent contains only safe codes/status/error metadata. The error
	// text is generated by internal providers, never by an external secret.
	o.enqueue(completionLog{Type: "completion", Event: event})
}

func (o *jsonlObserver) Close() error {
	o.once.Do(func() {
		close(o.queue)
		o.wg.Wait()
	})
	return nil
}
